#!/usr/bin/env ruby
require 'rubygems'
require 'couchrest'

puts "Importing views..." unless ENV['SILENTIMPORT']

db_uri = ARGV[0] || File.read(File.join(File.dirname(__FILE__), "..", "database_uri")).strip

puts "Using database: #{db_uri}" unless ENV['SILENTIMPORT']

db = CouchRest.database!(db_uri)
db.recreate!

view_files = Dir[File.join(File.dirname(__FILE__), "views", "*", "*.*.js")]
views = {}
view_files.each do |vf|
  if vf =~ /^(.*)\/(\w+)\/(\w+)\.(\w+)\.js$/
    views[$2] ||= {}
    views[$2][$3.to_sym] ||= {}
    views[$2][$3.to_sym][$4.to_sym] = File.read(File.expand_path(vf))
  end
end

docs = []

views.each do |design, options|
  docs << {"_id" => "_design/#{design}", :views => views[design]}
end

db.bulk_save(docs) unless ENV['SKIPADD']